export default {
    INIT_HOME_SCREEN: "INIT_HOME_SCREEN",
    HOME_SCREEN_BEGIN: "HOME_SCREEN_BEGIN",
    HOME_SCREEN_RESET: "HOME_SCREEN_RESET",
    HOME_SCREEN_ERROR: "HOME_SCREEN_ERROR",
    HOME_SCREEN_PRODUCT: "HOME_SCREEN_PRODUCT",
    HOME_SCREEN_UPDATE_COUNTER: "HOME_SCREEN_UPDATE_COUNTER",
};
