export default {
    INIT_CART_SCREEN: "INIT_CART_SCREEN",
    CART_SCREEN_BEGIN: "CART_SCREEN_BEGIN",
    CART_SCREEN_RESET: "CART_SCREEN_RESET",
    CART_SCREEN_ERROR: "CART_SCREEN_ERROR",
    CART_SCREEN_PRODUCT: "CART_SCREEN_PRODUCT",
    CART_SCREEN_UPDATE_COUNTER: "CART_SCREEN_UPDATE_COUNTER",
    CART_SCREEN_PRE_SELECT_PRODUCT: "CART_SCREEN_PRE_SELECT_PRODUCT",
    CART_SCREEN_SELECT_PRODUCT: "CART_SCREEN_SELECT_PRODUCT",
    CART_SCREEN_PRODUCTS: "CART_SCREEN_PRODUCTS",
};
